language: python

python:
 - 3.6

install:
 - pip install  -r requirements.txt
 - pip install coveralls

before_script:
  - psql -c 'create database tests_db;' -U postgres
script:
 - nosetests --with-coverage --cover-package=app

after_success:
- coveralls
